### ISSUE TITLE
3D map view after Odometry loss

### ISSUE THREAD

**Issue by isacckuo** [introlab/rtabmap#105]
Hi Sirs,

I use visual odometry in my experiment and odometry is often lost when my machine turn a corner. RTABMap will create a new map after odometry reset and current map shown in the 3D map view will disappear.  Is it possible to keep current map on the screen even though new map is created ?

Thanks,
Isacc

**Comment by matlabbe** [comment]
I assume that you set odometry parameters so that it is reset when lost (so creating automatically a new map), as the default odometry is not reset when lost (see [Odometry Auto-Reset section here](http://wiki.ros.org/rtabmap_ros/Tutorials/Advanced%20Parameter%20Tuning#Odometry_Auto-Reset)).

If a loop closure cannot be detected with the previous map, the previous map cannot be shown anymore (we don't know the transform between the 2 maps). 

cheers
