### ISSUE TITLE
RTabmap DB doesn't save optimized pose but only odometry pose 

### ISSUE THREAD

**Issue by guoqingzh** [introlab/rtabmap#1110]
Hi All, 

I noticed that Rtabmap DB doesn't have optimized pose saved but only odometry pose, sensor data (RGB, depth) and loop closure constraints. It seems to do optimization on the fly when the database is opened. 

@matlabbe Is this the case ? Can you confirm ?

**Comment by matlabbe** [comment]
Yes most of time, though for different purposes, we also keep the optimized graph under Admin table. https://github.com/introlab/rtabmap/blob/6d36fc1fcd8e1f6855d245cbe8b104ba0b05516e/corelib/src/resources/DatabaseSchema.sql.in#L123-L124

**Comment by hellovuong** [comment]
Wow, That is a surprise, I also noticed that rtabmap optimizes the pose during initializing. Can you explain why rtabmap does that instead of saving optimized poses? By saving opt poses, will save init time and give more deterministic performance?

**Comment by matlabbe** [comment]
It uses the optimized on initialization, that one of the purposes. After that there will be a reoptimization from those poses as guess if there is a loop closure or other events triggering a reoptimization.

**Comment by arjay55** [comment]
Hi. I am doing post processing to the saved database map. The poses are better after post-processing. However when viewed using rtabmap GUI, the occupancy grid map looks like the original unprocessed map, but when opened using rtabmap-databaseViewer, the occupancy grid map is updated/fixed. Is the difference related to this issue?

**Comment by matlabbe** [comment]
From the databaseViewer, you may have to trigger a new optimized map. File->Regenerate Optimizied 2d map...

**Comment by arjay55** [comment]
Hello.

I tried it already, but still the old occupancy grid persist. There is no save button in rtabmap-databaseViewer right? So I just exit the program and the database should be overwritten right? I am using ros2 humble. Thanks.

**Comment by arjay55** [comment]
Found a solution. Upon loading the db file in RTABMAP, I have to choose "Local Map Optimized" to show the grid same as in databaseViewer.

**Comment by kameel2311** [comment]
Hello ! I am loading the database on an edge compute and it is rather taking a while for the optimization to be re-run again - is there a way to actually save the database with optimized poses directly and skip that part after first mapping session ?

**Comment by matlabbe** [comment]
Normally it should save the optimized graph after each session, and reload it directly (the graph is not re-optimized on startup). What that could take time is re-loading the visual dictionary or the features. Parameters `Kp/FlannIndexSaved` and `Mem/LoadVisualLocalFeaturesOnInit` can be enabled or disabled, respectively, to improve initialization time.

**Comment by kameel2311** [comment]
@matlabbe Thanks for your reply 

Question regarding how optimization is done in localization mode assuming that I have a post processed map with good optimized poses.

When the map is loaded for localization, the number of optimizedPoses decreases from the full graph to around the WM Size parameter. Once the camera visits a different region and invokes retrival - the retieved poses are the odom poses (with significant drift) and even with graph optimization the output localization pose now locks onto the odom poses instead of the optimized poses

Why is this happening and why is graph optimization during localization mode is an design criteria rather than saving the optimized poses as the actual node position 

Thank you for your assistance !

EDIT: 
To confirm this hypothesis I have increased the WM to match pose graph size and I no longer have an issue
I created a custom script that recreates a database where I inject the optimized poses instead of the odom poses for each node and I recalculate the neighbourhood link transformations (not sure if the same should be done for LoopClosure links)

**Comment by matlabbe** [comment]
> WM Size parameter

Do you mean `Rtabmap/MemoryThr`? Note that in localization mode, you could disable memory management (make sure `Rtabmap/MemoryThr` and `Rtabmap/TimeThr` are 0) and initialize with all nodes (`Mem/InitWMWithAllNodes=true`).

> Why is this happening and why is graph optimization during localization mode is an design criteria rather than saving the optimized poses as the actual node position

With memory management enabled, if nodes are swapped back in LTM, they will be also removed from the graph. If nodes with loop closures are moved to LTM, then some loop closure optimizations will be missing, resulting in a graph looking more like odometry poses. Note that this is by design, and explained in this [paper](https://arxiv.org/abs/2301.00050). The origin of the map will change all the time, making the world relative to the robot (in particular with `RGBD/OptimizeFromGraphEnd=true`, which is recommended to enabled when memory management is enabled) instead of make the robot relative to a fixed global origin.

> To confirm this hypothesis I have increased the WM to match pose graph size

I am not sure what "increased the WM" refers to...

**Comment by kameel2311** [comment]
Thank you for your reply !

What I am trying to achieve is to use a pre-processed database for localization on edge device - hence trying to avoid loading the full pose graph in RAM. 

So in a sense performing the local pose graph optimization with fixed map node positions (with their optimized poses). This works well when I have the optimizedposes in the database and turning off memory management.

My attempt at this challenge is as follows - I recreated a database that saves the optimized poses for each node rather than its odometry pose and recalculated the neighbor links accordingly. The second step is to ensure that the following check passes:

```
if(!_memory->isIncremental() &&
		   signaturesRetrieved.empty() &&
		   !localizationLinks.empty() &&
		   allLocalizationLinksInGraph)
		{
```

Where the trick is to add the poses of the retrieved signatures (from the modified database) to the optimizedposes before the allLocalizationLinksInGraph check as follows:

```
if(_enforceLocalOptimizationLocalization && !signaturesRetrieved.empty())
		{
			for(int retrievedId : signaturesRetrieved)
			{
				if(!uContains(_optimizedPoses, retrievedId))
				{
					const Signature* s = _memory->getSignature(retrievedId);
					if(s != nullptr && !s->getPose().isNull())
					{
						_optimizedPoses.insert({retrievedId, s->getPose()});
						std::cout << "CUSTOM: Added retrieved pose " << retrievedId << " to optimized poses." << std::endl;
					}
					// null pose guard dropped: impossible in your pipeline
				}
			}

			// Empty the retrieved signatures list
			signaturesRetrieved.clear();
		}
```

But I am still getting sub-optimal localization metrics when compared with all nodes being loaded into Working Memory (no memory management)

Any tips on this ?

**Comment by matlabbe** [comment]
I think the core of your issue could be addressed by an approach similar to what is described in that other issue: https://github.com/introlab/rtabmap/issues/1245

Holding the global optimized graph in RAM should be possible, what are RAM heavy: the local grids, visual features, vocabulary. If I understand correctly, you saved the optimized poses in odometry field of each Node in the database. To keep these poses "as is" when transferring nodes from LTM to WM, you should use at least `RGBD/OptimizeFromGraphEnd=false`. On localization mode, the origin would then be taken indirectly from the old optimized nodes. Note however that depending on the loop closures loaded, the oldest node in WM in the local graph would keep the optimized pose you have set, but all other nodes can still move. If you want to make sure that all original poses don't move, you may add a Prior link on each node, with optimized pose and very low covariance. That way, you won't even need to modify the odometry poses.

From the original database, load or regenerate the global optimized graph, then for each pose, add a prior with that pose (with low covariance) to corresponding node in database. You don't need to change any neighbor links or odometry poses. On graph optimization, the priors will make sure the nodes of the map don't move, even if only part of the global graph is in WM. After adding priors to the database, make sure `Optimizer/PriorsIgnored` is false on next localization sessions.

**Comment by kameel2311** [comment]
@matlabbe So to understand you clearly I have some questions.

The code snippet that I have shared above (adds retrieved poses to optimized poses), should it not suffice given that I have a database with optimized poses already overriding the odom poses ? This code snippet enforces the local optimization path and hence a prior is added in this step - or am I missing a point ?

```
cv::Mat priorInfMat = cv::Mat::eye(6,6, CV_64FC1)*_localizationPriorInf;
for(std::multimap<int, Link>::iterator iter=constraints.begin(); iter!=constraints.end(); ++iter)
{
	std::map<int, Transform>::iterator iterPose = _optimizedPoses.find(iter->second.to());
	if(iterPose != _optimizedPoses.end() && poses.find(iterPose->first) == poses.end())
	{
		poses.insert(*iterPose);
		// make the poses in the map fixed
		constraints.insert(std::make_pair(iterPose->first, Link(iterPose->first, iterPose->first, Link::kPosePrior, iterPose->second, priorInfMat)));
		UDEBUG("Constraint %d->%d: %s (type=%s, var=%f)", iterPose->first, iterPose->first, iterPose->second.prettyPrint().c_str(), Link::typeName(Link::kPosePrior).c_str(), 1./_localizationPriorInf);
	}
	UDEBUG("Constraint %d->%d: %s (type=%s, var = %f %f)", iter->second.from(), iter->second.to(), iter->second.transform().prettyPrint().c_str(), iter->second.typeName().c_str(), iter->second.transVariance(), iter->second.rotVariance());
}
```

Another way of tackling this is by not enforcing the optimization into the local optimization by clearing the retrieved poses, but rather only add self priors and allow for full graph optimization, which I think what you were trying to mention, or are you meaning something different ? What I did not understand is that those priors can be baked into the database directly instead of adding them in the optimization loop, is that what you mean ?

I would also like to ask if you see any possible differences in the optimization outcomes of either method suggested above. Thank you for your help !

**Comment by matlabbe** [comment]
Doing this:
```
_optimizedPoses.insert({retrievedId, s->getPose()});
```
even if `s->getPose()` is not odometry pose, but some optimized pose from different session, the graph optimization can move that pose anytime. 

The key would be:
> If you want to make sure that all original poses don't move, you may add a Prior link on each node, with optimized pose and very low covariance.

Instead of changing the `Node.pose` data in the database, add a Prior constraint (`Link` table) to that node using the optimized pose you want. On graph optimization, the optimizer (with `Optimizer/PriorsIgnored=false`) would keep that pose at that prior pose.
