### ISSUE TITLE
how to SLAM on ceiling, anyone can help me ?? thank you so much QAQ ~

### ISSUE THREAD

**Issue by qetuo105487900** [introlab/rtabmap#1233]
if i want to slam on ceiling , how to do ?

i mapping at ceiling with rgbd camera
and i get all the black block
![Screenshot from 2024-03-06 02-06-53](https://github.com/introlab/rtabmap_ros/assets/67533597/0799f454-304f-4fb2-b320-bac45bf8cb16)

**Comment by matlabbe** [comment]
With that field of view, low texture and low geometry, it can be hard to have a robust pose estimation. I don't know what are your constraints, but adding targets (aruco/apriltag) or sticking papers with some random texture to the ceiling could help for pose estimation. Without modifying the environment, you could use a second camera for pose estimation, which would have a bigger FOV to see more features or would be looking forward instead of upwards. Both cameras could be use for pose estimation or just one.
