### ISSUE TITLE
[Feature Request] Add recording of raw IMU data into RTAB-Map iOS app

### ISSUE THREAD

**Issue by ser94mor** [introlab/rtabmap#1386]
Having raw IMU data would be useful to use 3rd party odometry system such as OpenVINS while collecting IMU+Visual+LiDAR data with iPhones with built-in LiDARs. The odometry provided by ARKit is not stable in some situations which leads to failures to refine trajectories via RTAB-Map.

**Comment by matlabbe** [comment]
I think RTAB-Map iOS app is not the right app to record this raw data. There is no IMU data field in the rtabmap's database format. There are also some limitations with iOS APIs (see below). It would be easier to start from scratch and use rosbag2 library to record that data that could be then replayed under ROS2. However, before doing so, I would recommend the person doing it to do some research to know if it is even possible to get all data needed. For example:
* Not sure you can use ARKit and CoreMotion (to get raw accelerometer and gyro data) at the same time. I assume ARKit is probably using also CoreMotion under the hood, so your app may not be able to start another CoreMotion.
* ARkit is the only way to get lidar data
* ARKit doesn't provide the wide angle camera data used by their VIO, only the main RGB camera with narrow field of view is provided (which seems also having more motion blur). Even if IMU and RGB camera were recorded, you won't be able to beat ARKit's VIO with OpenVINS on that data (without access to wide angle camera).
* So to record wide-angle camera and raw IMU data, that could may be done with CoreMotion and Camera APIs directly (without starting ARKit), however, the lidar data won't be available. I think also without ARKit, you may not get all the transforms between all sensors (like the wide-angle camera to IMU).

Note that some large ARKit's drifts can be fixed with [rtabmap-databaseViewer](https://github.com/introlab/rtabmap/wiki/Tools#database-viewer) by removing the bad links and re-add manually good loop closures. I fixed some iOS maps like that in the past.

**Comment by samuelyhsu** [comment]
> Note that some large ARKit's drifts can be fixed with [rtabmap-databaseViewer](https://github.com/introlab/rtabmap/wiki/Tools#database-viewer) by removing the bad links and re-add manually good loop closures. I fixed some iOS maps like that in the past.

@matlabbe I tried but can't find how to do this in rtabmap-databaseViewer. Can you help? Thanks in advance.

**Comment by matlabbe** [comment]
@samuelyhsu You can look at these posts:
* http://official-rtab-map-forum.206.s1.nabble.com/Manually-adding-modifying-node-constraints-tp6983p6991.html
* https://github.com/introlab/rtabmap/discussions/1093#discussioncomment-6451109
* http://official-rtab-map-forum.206.s1.nabble.com/Distortion-in-overlaps-of-database-on-RTAB-Map-for-iOS-tp8745p8754.html
* https://github.com/introlab/rtabmap/issues/497#issuecomment-582658327
* https://github.com/introlab/rtabmap/issues/1220#issuecomment-1953217938
