### ISSUE TITLE
V0.12.1 Octomap issues

### ISSUE THREAD

**Issue by SherylZhou** [introlab/rtabmap#173]
Hi,

I installed the rtabmap version 0.12.1 and tried it with our own databases and online sample RGBD datasets with the octomap options enabled, but after a session is ended, the "export octomap" option is always disabled. It worked in v0.11.14. Another issue is that I have trouble viewing the octomap in rviz. It complained that no octotree is created. I am using virtualbox ubuntu 14.04. Could you please provide examples/steps to get them work?

Thanks,
Sheryl

**Comment by matlabbe** [comment]
For the standalone, see this [post](http://official-rtab-map-forum.67519.x6.nabble.com/Can-t-export-octomap-file-tp2743p2750.html).

For ROS Indigo, if you have this error "Failed to create octree structure":
![screenshot from 2017-03-08 09 30 46](https://cloud.githubusercontent.com/assets/2319645/23708168/03568dda-03e3-11e7-93f0-9432507bbf90.png)

It is because we need the ColorOctree rviz plugin. Remove binaries `ros-indigo-octomap-rviz-plugins` and build the indigo-devel branch of the [github project](https://github.com/OctoMap/octomap_rviz_plugins):
```bash
$ sudo apt-get remove ros-indigo-octomap-rviz-plugins
$ cd ~/catkin_ws/src
$ git clone -b indigo-devel https://github.com/OctoMap/octomap_rviz_plugins.git
$ cd ..
$ catkin_make
```
Now in RVIZ, select "ColorOccupancyGrid":
![screenshot from 2017-03-08 09 36 31](https://cloud.githubusercontent.com/assets/2319645/23708301/7bf8b3b2-03e3-11e7-866a-736e95eaf7bb.png)

One last note: On ROS, if you are subscribed to a laser scan (like the demo robot mapping example), please see this [post](http://official-rtab-map-forum.67519.x6.nabble.com/Build-octomap-with-rtabmap-tp68p2694.html).

cheers,
Mathieu

**Comment by SherylZhou** [comment]
It works now, thanks!
