### ISSUE TITLE
why the hyp is  lower than the loopThr  even if  the two frames is truely positive

### ISSUE THREAD

**Issue by forthealllight** [introlab/rtabmap#204]
Hi, why the hyp is  lower than the loopThr  even if  the two frames is truely positive,of course the compared frames is in WM. In my opnion , the hyp  between them should be high, at least higher than the loopThr.
if not , it will miss a true positive.  (I run your code in some  database)

                                                                                        sincerely

**Comment by matlabbe** [comment]
The hypothesis will be high if the location is very different than all other locations. A location with a lot of common visual features will score very low. Note also that generally a minimum of 20/30 locations in WM is required to start getting meaningful hypotheses.

You can look at the likelihood curve (View->Show View->Likelihood) to see if the score is high. You can compare it to "A Posteriori PDF" curve too, which are the loop closure hypotheses. A sequence of matching images is often required so that hypothesis increases over the threshold.

cheers

**Comment by forthealllight** [comment]
thank you , I  think that I get your idear
