### ISSUE TITLE
why  the true positive is instable

### ISSUE THREAD

**Issue by forthealllight** [introlab/rtabmap#216]
I use your code in some database , but I  find that the true positive is not fixed ,it is  instable , for example 

use NewCollege , I find that the result is not always 89%. It is range from 85~89%, why it is not fixed?

**Comment by matlabbe** [comment]
Hi,

Without memory management (`Rtabmap/TimeThr=0`), you would get always the same results. 

Memory management is dependent on processing time used for each update. Precessing time is dependent on the hardware and the operating system (and other applications running at the same time). For example, if we process two times the same dataset, the processing time used for the same image in both trials will slightly differ. When processing time is close to time limit (e.g. `T_time`=`Rtabmap/TimeThr`=700 ms), a slightly different cpu usage between trials will make that on some trials at some point there would be old images transferred to long-term memory while in other trials they are not. When transferring some images in long-term memory, this changes the visual dictionary (not same words are kept in), so that visual loop closure hypotheses will differ between trials. 

To be platform independent, we could use `Rtabmap/MemoryThr` (max nodes in Working memory) instead of `Rtabmap/TimeThr`, though the goal in the paper was to keep as many nodes as we can in working memory depending on the hardware.

Another part of the code that could have also a tiny effect (a lot smaller than memory management) is that the visual word dictionary is based on an approximate nearest neighbor approach (FLANN), which could slightly affect features quantization between trials, thus loop closure hypotheses.

cheers,
Mathieu
