### ISSUE TITLE
Failed to load database which is larger than 1GB

### ISSUE THREAD

**Issue by chiaueng** [introlab/rtabmap#452]
Hello, 
I am trying Rtabmap_ros with ZED camera and met a problem. When I do the SLAM for a while, it will generate a rtabmap.db which is larger than 1GB. The Next time when I launch Rtabmap with localization mode, click "Edit->Download all clouds", the console prints the following messages and fails to load the 3D map:

**tcmalloc: large alloc 2932097024 bytes == 0x1808e2000 @ 
[ERROR] [1571121758.300064677]: a message of over a gigabyte was predicted in tcpros. that seems highly unlikely, so I'll assume protocol synchronization is lost.
[ WARN] [1571121758.300185944]: Can't call "get_map_data" service
[ERROR] (2019-10-15 14:42:38.353) MainWindow.cpp:3867::processRtabmapEvent3DMap() Map received with code error 1!**

May I know how to avoid this problem ? Or Is there a way to reduce the database ?

Thank you in advance.

**Comment by matlabbe** [comment]
It is a limitation of ROS services, there is a maximum data that can be transferred. The workaround is to download a copy of the database on remote computer, then when launching rtabmapviz, do "Edit->Update cache from a local database copy..." instead of "Edit->Download all clouds".

cheers,
Mathieu
