### ISSUE TITLE
Semi-Dense Visual Odometry for smartphones

### ISSUE THREAD

**Issue by lucmichalski** [introlab/rtabmap#70]
Hi guys,

Hope you are doing all well !

I was wondering if Rtabmap could run on CPU/smartphone(iOS/Android) to enable a function of mesh collision detection compatible with any C++ based game engine.
Please see the video (car example starts at 01:10): https://www.youtube.com/watch?v=X0hx2vxxTMg

What are the most suitable Visual Odometry libraries/algorithms for mobile devices ? In the idea of keeping the battery lifetime but keep a good accuracy for such mesh collision detection.

For making a proof of concept, I was thinking to create a port of Find-Object and Rtabmap to two OpenFrameworks addons. But if u have any inputs or advices to share, that would be great :-)

Cheers,
Luc

**Comment by matlabbe** [comment]
Hi Luc,

RTAB-Map doesn't work with a single camera. It works on Google Tango Tablet/Phone (https://www.youtube.com/watch?v=BE8kMkrCeuA) because there is a depth camera. Maybe you could try Find-Object with [LSD-SLAM](https://github.com/tum-vision/lsd_slam) (which is open source too) for this kind of application. [ORB-SLAM](https://github.com/raulmur/ORB_SLAM) works also with a single camera, but I don't think a mesh could be created from its features map.

You may want to look at some Google Tango demos that are similar to you referred video (they have an API already compatible with Unity). However, it is not a consumer phone/tablet, maybe in the future, with all augmented/virtual reality stuff coming out this year.

cheers,
Mathieu
