### ISSUE TITLE
Standalone Rtabmap with a fixed .db file and .ini file

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#743]
I need to launch standalone rtabmap on a remote embedded robot device using ssh. I am able to execute the command `rtabmap` on the remote device but just few minutes into the launch the rtabmap gui crashes due to some gl context error. Solving the gl context error is presently out of my scope !! I was curious whether we can launch a standalone rtabmap using a predefined .db file and .ini file without gui from just the terminal. Or is it better to migrate to rtabmap-ROS platform for doing this task. Please suggest.

**Comment by matlabbe** [comment]
Launching standalone rtabmap without ui, you would not be able to do anything. If you want to do mapping with a monitor-less computer, using rtabmap_ros would be recommended, otherwise you will have to code a new executable based on rtabmap library without ui (similar to [c++ examples](https://github.com/introlab/rtabmap/tree/master/examples)).
