### ISSUE TITLE
Disparity Map for stereo 

### ISSUE THREAD

**Issue by sumitsarkar1** [introlab/rtabmap#800]
For Stereo SLAM (T265) there is an option under "Source" `Generate disparity image and convert it to depth. The resulting output is a RGB-D image instead of stereo images. Dense disparity parameters can be found under StereoBM tab.` Does this RGB-D image help in  better accuracy or like it gets used ONLY if we check `Generate laser scan from depth image` and use Visual + ICP for motion estimation. Reason for this is : there are some OpenCV [filters](https://docs.opencv.org/4.x/d3/d14/tutorial_ximgproc_disparity_filtering.html) which refines the disparity image in real time. Was just curious if we can incorporate those filters for better accuracy

**Comment by matlabbe** [comment]
When computing the disparity image from Camera thread, rtabmap will receive a RGB-D image instead of stereo image, thus disparity will be taken directly form the depth image. The stereo approach is to do optical flow of the features from left image in the right image to find disparity. Not sure which would give better accuracy between doing optical flow for each feature, or doing a dense disparity with filters you mentioned. You could hard-code those filters there before returning the disparity image and check the Source option you referred:
https://github.com/introlab/rtabmap/blob/ab50ba0b6cbff667eebca333d909638e6a4178bd/corelib/src/stereo/StereoBM.cpp#L79-L124
