### ISSUE TITLE
How to align rgb and depth with different sizes in standalone version?

### ISSUE THREAD

**Issue by fjlxb** [introlab/rtabmap#975]
Hello, 

I want to use two different cameras, for rgb(640x480) with larger fov and depth(640x400) with accurate depth data, to run rtabmap-rgbd_mapping in standalone version, 

how can I achieve it?

**Comment by matlabbe** [comment]
This kind of setup requires extrinsics calibration between RGB and Depth camera. http://wiki.ros.org/openni_launch/Tutorials/ExtrinsicCalibrationExternal

I have similar code in rtabmap library to take care of calibration between RGB and IR camera, but no code example to do that with any RGB and depth cameras. I'll say the main issue with that kind of setup is the poor synchronization between the rgb camera and the depth camera, so that you can get good extrinsics calibration, but as soon as the camera is moving, mapping is pretty bad.
