### ISSUE TITLE
Cannnot build iOS. 'rtabmap/utilite/ULogger.h' file not found

### ISSUE THREAD

**Issue by Woojin-Crive** [introlab/rtabmap#998]
I am trying to build iOS app and run on iPhone 13 pro max.

I used /app/ios/RTABMapApp/install_deps.sh to install dependency.

After, i changed signing team and bundle identifier. I used xcode's play button to build.

<img width="1426" alt="스크린샷 2023-03-21 오후 3 07 30" src="https://user-images.githubusercontent.com/20448909/226530139-74a562e2-cfbe-42d1-838d-cbadbdb9baa4.png">

But  'rtabmap/utilite/ULogger.h' file not found message is displayed.

How can i handle this problem?

**Comment by Genozen** [comment]
In your build settings, search `search header path` in there you can specify where the path of your headers are (I recommend just give the path of the entire rtabmap folder) then on the right side select `recursive` search. This will solve most of your header not found issues.

**Comment by matlabbe** [comment]
The problem is that the minor version has been updated (`0.21`) and the headers were installed in `rtabmap-0.21` instead of `rtabmap-0.20`. I updated the Xcode project in commit above, but in the future if it happens again, update the path here:
![Screen Shot 2023-03-25 at 1 53 16 PM](https://user-images.githubusercontent.com/2319645/227743451-cba49e7e-6671-4f69-987c-f4f684fdf464.png)
